### ISSUE TITLE
Explicit, additional CPU Type support (S7-1200, S7-1500, etc...)

### ISSUE THREAD

**Issue by killnine** [killnine/s7netplus#1]
The existing CPU Types may work for other devices, but I don't know for sure. For example, using the S7300 type allows me to communicate with an S7-1200 just fine.

Other CPU types I would like to investigate:

+ S7-1200
+ S7-1500
+ ET200M
+ SIMOTION Controllers

**Comment by olesa79** [comment]
This works for me for connecting to S7-1500 (fixed values instead of rack/slot).  It's the only change I had to make.

 case CpuType.S71500:
                        // Eigener Tsap
                        bSend1[11] = 193;
                        bSend1[12] = 2;
                        bSend1[13] = 0x10;
                        bSend1[14] = 0x2;
                        // Fremder Tsap
                        bSend1[15] = 194;
                        bSend1[16] = 2;
                        bSend1[17] = 0x3;
                        bSend1[18] = 0x0;
                        break;

**Comment by mesta1** [comment]
S7 1200 and S7 1500 are now supported.

**Comment by olesa79** [comment]
You still need the Slot (and possibly the rack) for 1500.  I don't know specifics, but just yesterday I had to use slot 1 to connect (probably connected to a CP)
bSend1[18] = Slot;

**Comment by mesta1** [comment]
Ok I need to investigate a bit on this. I remember too that for S7 1200 and 1500 you need slot 1, let me check some documentation then i'll get back with a fix.

**Comment by mesta1** [comment]
Based on this page (http://settimino.sourceforge.net/comp_1200.html) and several posts around internet, it seems that S71200 and S7 1500 needs (rack = 0; slot = 0).
If you have the equipment, can you verify if that's true ?

**Comment by olesa79** [comment]
On the test I did a couple of days ago:
If I connected to the CPU's IP address I had to use bSend1[18] = 0
If I connected to the CP's IP address I had to use bSend1[18] = 1
In TIA Portal, the CPU is displayed as slot 1 and the CP as slot 2.
This is for 1500.  I've tested with 1200.

**Comment by mesta1** [comment]
With CP you mean Siemens CP 1543-1 ? External ethernet card ?

**Comment by mesta1** [comment]
Added rack and slot on S7 1500.
