### ISSUE TITLE
Still can't get rid of 'NullReferenceException' while class or structure reading. 

### ISSUE THREAD

**Issue by Mallowan** [killnine/s7netplus#109]
Hello everyone my issue is still not resolved. :)
While playing around, I'm getting  **NullReferenceExceptio**n **'Object reference not set to an instance of an object.'** Despite of  created 1Byte size DB1 in Step7 project or 1Byte size Structure. As was described in #105. 
Can't get what's wrong. Thank in advance!
Here is a code I used.

```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using S7.Net;

namespace WindowsFormsApplication1
{
    public partial class Form1 : Form
    {
        Plc plc = null;

        public Form1()
        {
            InitializeComponent();

            Plc plc = new Plc(CpuType.S7300, "127.0.0.1", 0, 2);


            plc.Open();

            if (!plc.IsConnected)
            return;


        }

        public class DB1
        {
            public bool varBool0 { get; set; }
            public bool varBool1 { get; set; }
            public bool varBool2 { get; set; }
            public bool varBool3 { get; set; }
            public bool varBool4 { get; set; }
            public bool varBool5 { get; set; }
            public bool varBool6 { get; set; }
            public byte varByte7 { get; set; }

        }

        private void button1_Click(object sender, EventArgs e)   //Button "Read Class"
        {

            DB1 db1 = new DB1();
            plc.ReadClass(db1, 1);

        }

        public struct DB1_Structure1
        {
            public bool varBool0;
            public bool varBool1;
            public bool varBool2;
            public bool varBool3;
            public bool varBool4;
            public bool varBool5;
            public bool varBool6;
            public bool varBool7;
        }




        private void button2_Click(object sender, EventArgs e)   //Button "Read Structure"
        {
           DB1_Structure1 db1_structure1 = (DB1_Structure1)plc.ReadStruct(typeof(DB1_Structure1), 1);
        }
    }
}

```
Created DB1 with 1Byte size.
![db1](https://user-images.githubusercontent.com/37699980/38978370-de5c3ef8-43bf-11e8-8f69-b6ed10634988.jpg)
![readclass_issue](https://user-images.githubusercontent.com/37699980/38978867-523be8cc-43c1-11e8-91d2-c73c47e20fe7.jpg)

**Comment by Mallowan** [comment]
``

**Comment by rapha-dev** [comment]
@Mallowan 
You have defined "plc" twice. First in class and second in Form1(). The instance used in button1_Clock() is never initialized.

It should be `plc = new Plc(CpuType.S7300, "127.0.0.1", 0, 2);` if you want to use the class defined instance.

You also want to add some error handling, i.e. not connected to PLC.

**Comment by Mallowan** [comment]
yes, this is working.
![plc_new_plc](https://user-images.githubusercontent.com/37699980/38985129-2c28d37e-43d1-11e8-93a1-efaf68e96006.jpg)

> You also want to add some error handling, i.e. not connected to PLC.

>

**Comment by rapha-dev** [comment]
Keyword here is [Watch](https://docs.microsoft.com/en-us/visualstudio/debugger/watch-and-quickwatch-windows).

**Comment by Mallowan** [comment]
> You have defined only 7 bools and 1 byte. Keep in mind 1 byte = 8 bits (bools).
> Also the last byte is not "visible" in DB1 (PLC), it means it is not usable by PLC program (at least not symbolic) but still exists.
> 
@rapha-dev  I'm sorry, but I've defined 1Byte or 8 Bools, as seen on the screenshot above (VarBool0...varBool7) and in the DB1 (Varbool0...VarBool7).

> Set a Watch on Variables
Separate thank.

Mallowan

**Comment by rapha-dev** [comment]
Have a look at the last "bool" in `class DB1`, it is a byte instead.
Your `public struct DB1_Structure1` consists of 8 bools.

From your original post:
```
public class DB1
        {
            public bool varBool0 { get; set; }
            public bool varBool1 { get; set; }
            public bool varBool2 { get; set; }
            public bool varBool3 { get; set; }
            public bool varBool4 { get; set; }
            public bool varBool5 { get; set; }
            public bool varBool6 { get; set; }
            **public byte varByte7 { get; set; }**

        }
```
PLC DB1 looks good.

**Comment by Mallowan** [comment]
yes, later I have noticed that TYPO and corrected.

Mallowan

**Comment by mesta1** [comment]
Closing as solved (code error on constructor).
