### ISSUE TITLE
Read() doesn't remove whitespaces in variable (parameter)

### ISSUE THREAD

**Issue by rapha-dev** [killnine/s7netplus#114]
When reading variables from a SQL-Server table they contain some whitespaces, as shown here.
![read1](https://user-images.githubusercontent.com/814049/39239954-b484cb1e-4882-11e8-8212-dcf2d8d41f8c.PNG)

Maybe it is better to Trim() excess characters or use an Regex as described [here](https://stackoverflow.com/a/14591148/6874271).

Using Trim() produces a readable address and doesn't lead to WrongVarFormat error.
![read2](https://user-images.githubusercontent.com/814049/39240043-fc2c723c-4882-11e8-8021-f36b3398bcad.PNG)

Best regards.

Edit: Some more investigation on the whitespaces: It is a Unicode non-breaking space (bytes C2A0).

**Comment by mycroes** [comment]
My opinion: this doesn't belong in a communications library. I don't know how you get your data in the database, but logically I'd say you forgot about input sanitizing, you should've made sure the data is valid before storing it in the database.

My proposal for this issue is to close as invalid.

**Comment by rapha-dev** [comment]
You are right, this should not be part of this library. Since it is it should work as expected.

Closing this as it is not a "normal" whitespace.
