### ISSUE TITLE
What exactly means second number in the reading DB class method?

### ISSUE THREAD

**Issue by Mallowan** [killnine/s7netplus#122]
Hello there,
I'm confused...
While testing I didn't use numbers of DBs large than "2" and everything was working fine.
For example:

```
DB1 db1 = new DB1();
plc.ReadClass(db1, 1); // reading DB1

DB2 db2 = new DB2();
plc.ReadClass(db2, 2); // reading DB2
```
 I tried to read DB called DB9 and I've got an exception. The DB9 itself is equal one Byte, and I tried to increase that up to 2 Byte. No matter, that doesn't work...
![db9_reading](https://user-images.githubusercontent.com/37699980/40623014-50f1af14-62ad-11e8-8a3b-cff70adde024.jpg)

So I would like to know what really means second number in the reading method. Should there be '9'?

> •	startByteAdr: specified the first address of the byte to read (the default is zero).

It seems, this contradicts with what I did with DB1, DB2. I confused whether second number must be 'DB number' or 'number of first address of the byte'.

Thank you in advance!

P.S. At the same time DB1, DB2 are being read perfectly. So, I don't understand all this. Hardware: S7-1500, Software: TIA V15.

**Comment by rapha-dev** [comment]
Hi,

your ReadClass signature would lead to `public int ReadClass(object sourceClass, int db, int startByteAdr = 0)`, where startByteAdr is optional and defaults to 0.

So `plc.ReadClass(db9, 9)` is correct if you want to read from DB9 starting at byte 0.

**Comment by Mallowan** [comment]
@Rapha-dev,
I'm sorry. That's amazing TIA portal...  As they say, 'The morning is wiser than the evening'. Sometimes TIA requires whether a reboot of OS, whether a reboot of TIA itself. I didn't that catch. Just I had run my laptop today morning and yesterday's code has became working... ) Awesom stuff...

**Comment by mycroes** [comment]
@Mallowan Could you close the issue please? No need to keep it open.
