### ISSUE TITLE
Writing a short[] to plc forgets byteswap for the shorts

### ISSUE THREAD

**Issue by eddydeboer** [killnine/s7netplus#126]
When writing a short[] to plc no byteswap is performed for the plc, so all written values are wrong.
We fixed it by swapping the bytes this way.
            var arr = new short[]{50, 256, 255, 128}
            //short array to bytearray
            var barr = S7.Net.Types.Int.ToByteArray(arr);
            for (var i = 0; i < barr.Length-1; i = i + 2)
            {
                var tmp = barr[i+1];
                barr[i + 1] = barr[i];
                barr[i] = tmp;
            }
            var err = Plc.Write(DataType.DataBlock, dbNo, offset, barr);

**Comment by rapha-dev** [comment]
@mycroes 
That's right, thanks for fix.
