### ISSUE TITLE
Number of PLC variable read at same time

### ISSUE THREAD

**Issue by SultanGeek** [killnine/s7netplus#13]
Hello everybody,
i use recently netplus for create an scada application under C#.So i want to know if i can create a polling program with a timer that poll for example 100 PLC variable at same time and display it in Windows form label.
The maximum bytes number that i what to read is 200 bytes.
What is the reliability of S7.NET for doing a something like that?
I never use this libray before i used SNAP7 library.
Thanks

**Comment by mesta1** [comment]
1) A single read reads maximum 200 bytes.
2) At the moment is not supported.
