### ISSUE TITLE
Bug : Have to connect with TIA to use library

### ISSUE THREAD

**Issue by murtagh38** [killnine/s7netplus#15]
Hello there,

I use the library for a project with ~10 S7-1212C. It works nearly fine, but it stills a bug :
The connection with the PLC works only if I was connected with it by TIA Portal at less one time. This means not to reboot the computer or I have to launch and connect each time with TIA.

I actually don't know why. If you have an answer or the same problem, please let me know right here.

Thank you

PS : sorry for my poor english

**Comment by Synless** [comment]
Up

Same here.

**Comment by mesta1** [comment]
As a reminder, the solution is to update the firmware of the plc.

**Comment by mesta1** [comment]
Closing as it is related to old firmware. Upgrading the plc firmware was the solution.
