### ISSUE TITLE
Problem with S7-312C with CP343-1 Lean

### ISSUE THREAD

**Issue by aitech** [killnine/s7netplus#17]
Hi!

I have used S7.Net for several projects now and it works great.

But now I have a project where I need to communicate with a 312C equipped with a CP313-1 Lean card (tried both version 2.2 and a 3.0 card), and I cant get it to work.

When I try with the example I only get "ERROR: Device is available but connection was unsuccessful!". I cant find any problem in the setup for the CP-card or CPU.

If I try with our HMI-software that we normally use (Beijer iX) the communication works great with the CPU.

Any ideas?

**Comment by jogibear9988** [comment]
if you use wireshark with the s7comm plugin, moste bytes in the s7 communication will be explained. Maybe then you find why your change works (in the wirkeshark nightly builds the s7comm plugin is already integrated!)

**Comment by mycroes** [comment]
I'm assuming this issue has long been fixed, but feel free to re-open if it doesn't work in the latest release (**0.2.0** at this time).
