### ISSUE TITLE
Bug : ReadBytes(DataType dataType, int DB, int startByteAdr, int count)

### ISSUE THREAD

**Issue by VagrantKm** [killnine/s7netplus#2]
//dataType = S7400
// DB = 8 , 
// startByteAdr=0 
// count = 300

Byte[] readBytes=ReadBytes(DataType dataType, int DB, int startByteAdr, int count)

if ( count > 222 )
{
     readBytes =nulll ://???? bug
}
else
{
readBytes =readBytes ;
}

**Comment by mesta1** [comment]
Already a task open to address PDU negotation: https://github.com/killnine/s7netplus/issues/21
