### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by olesa79** [killnine/s7netplus#22]
Can you add a license to this software?  I'm finishing an installer for my software that includes S7.NET+ and would like to have a license giving me the right to use this code :)

BTW - Jürgen was using a MIT License for his original work.

**Comment by mesta1** [comment]
I will add a MIT license in the next pull request.

**Comment by killnine** [comment]
Thanks, @mesta1. I was looking into different licenses and not sure which would be best. I'd like this project to be open for personal and commercial use.

**Comment by mesta1** [comment]
The original code was under MIT license, so we can't change it. 
You can find the original license here: https://s7net.codeplex.com/license
