### ISSUE TITLE
WrongVarFomat

### ISSUE THREAD

**Issue by combinu** [killnine/s7netplus#25]
Hi,

I have already used the old s7 library in the past and worked really fine.
Now we are going to connect to an s7-1200 plc and with this library it connects just fine.
The problem occurs when i try to read from the plc.

The var location is : DB1.DBW2
C# code: object s = plc1.Read("DB1.DBW2");
And i get WrongVarFormat.

Can you please help me out. Is there something new in this version that maybe i am missing?

Regards,

**Comment by mesta1** [comment]
On the bottom of this document there is the configuration to read from S7-1200 / 1500
http://snap7.sourceforge.net/snap7_client.html
