### ISSUE TITLE
PLC Close method doesn't handle the socket correctly

### ISSUE THREAD

**Issue by mesta1** [killnine/s7netplus#29]
Refer to: http://www.mesta-automation.com/siemens-s7-plc-c-s7-net-plc-driver/#comment-507

It seems that if I execute this code multiple times, I get "B" in output.

 ErrorCode connectionResult = plc.Open(); //open connection
if (connectionResult.Equals(ErrorCode.NoError))
{
    gB_Control.Enabled = true;
    tSrip_Conectado.Text = "A Text";
}
else
{
    tSrip_Conectado.Text = "B text";
}
plc.Close(); //close connection

**Comment by oiisamiio** [comment]
from MSDN:
https://msdn.microsoft.com/de-de/library/system.net.sockets.socket.disconnect(v=vs.110).aspx

so better use:
(set to Disconnect(true) if you want reuse Connection)

```C#
        public bool Close()
        {
            if (this._mSocket != null && _mSocket.Connected)
            {
                this._mSocket.Shutdown(SocketShutdown.Both);
                this._mSocket.Disconnect(false);
                this._mSocket.Close(100);
            }

            return this.IsConnected;
        }
```
