### ISSUE TITLE
Push based change notification

### ISSUE THREAD

**Issue by pietervp** [killnine/s7netplus#3]
Would it be possible (probably depends on hardware being used) to let the PLC send updates about register changes automatically to listeners?

As far as I know, if I want to monitor all the DB's in a PLC, we have to poll for the db values. So is there a way to turn this around? If so, could we implement such a 'listener'?

**Comment by mycroes** [comment]
I agree that s7netplus shouldn't be dealing with the polling. It can perfectly be done using extension methods or as a separate consumer of the s7netplus API, so there's no reason to include it in the library. Can this issue be closed? (The more issues there are, the smaller the chance is someone will try to fix them all).

**Comment by mycroes** [comment]
Closing as wontfix.
