### ISSUE TITLE
[S7-200]Reading  information from the Variable Memory.

### ISSUE THREAD

**Issue by Okalmas** [killnine/s7netplus#34]
Hello.

I've noticed that there is no code in the library for reading information stored in the Variable Memory  of the PLCs. I have done some research inside the code and noticed that when reading the memory, all you have to do is send an array of bytes through the comunnication socket, and then read the data sent  back from the PLC. 

I have the hypothesis that  reading from the Memory is analog to reading from the Variable Memory. So the Array of bytes sent to the PLC must be just slightly different. 

Does anyone know why the array of bytes, created in the ReadBytes() method have to have that format?
Where can I find documentation involving this kind of ethernet comunication with an S7200 PLC?

Thanks for reading. 

Okalmas

**Comment by mesta1** [comment]
S7-200 is not in active development, because it's obsolete equipment. 
If you or someone else wants to fix the bug, we will merge your pull request.
