### ISSUE TITLE
Written value is offset by 2 bytes

### ISSUE THREAD

**Issue by 2287728768** [killnine/s7netplus#509]

**Comment by mycroes** [comment]
Please provide an English description of your problem and add a minimal reproduction that shows when the issue happens.

**Comment by 2287728768** [comment]
When writing a value, there was a write object offset. The result that was supposed to be written to the first address was automatically postponed to the second address. How to solve this problem.

**Comment by 2287728768** [comment]
The DB address you want to write is DB1. DBW0.0, and the result is written to DB1. DBW2.0

**Comment by mycroes** [comment]
Please add a minimal reproduction. The behavior you're experiencing doesn't seem to be a known issue.

**Comment by 2287728768** [comment]
yes,Write value offset by 2 bytes

**Comment by mycroes** [comment]
Please add a minimal reproduction (code sample) that causes this problem.

**Comment by 2287728768** [comment]
Plc PLC20 = new Plc(CpuType.S71500, "192.168.12.254", 0, 1);
 PLC20.Open();
PLC20.Write(textBox2.Text, int.Parse(textBox1.Text));            //textBox2 To obtain the DB block address

**Comment by 2287728768** [comment]
The operating environment is Visual Studio 2017. 
PLC operates in a simulation environment
Thank you

**Comment by mycroes** [comment]
You're writing an `int`, which is 4 bytes, comparable to Siemens `DINT`. From your explanation of the issue I'm assuming you were expecting to write a `short`, or `INT` in Siemens terminology. Changing the code to `short.Parse(textBox1.Text)` will probably do what you expected.

**Comment by 2287728768** [comment]
such is the case. Thank you for explaining
