### ISSUE TITLE
Support for Optimized block Access for S7-1500?

### ISSUE THREAD

**Issue by SWOESS** [killnine/s7netplus#516]
As per the documentation, I can only find a line of text that seems to have been copied directly from the Snap7 Documentation.
This Line states that Optimized Block Access for S7-1500 PLC is not supported. 
Is this still true, or has this feature been implemented?
If not, are there plans to implement this in the future?

Kind Regards and keep up the great work!
SW Dev

**Comment by mycroes** [comment]
This is a duplicate of #323 and more recently #503.
