### ISSUE TITLE
[QUESTION] Operating System Restrictions

### ISSUE THREAD

**Issue by sebetci** [killnine/s7netplus#536]
## Type of Issue

- Question / Restrictions

## Description

Are there any restrictions on the use of this library in the following operating system?

* **OS Version:** Windows 10 IoT Enterprise CBB 64-Bit Operating System

**Comment by piyushh2229** [comment]
USE WINDOWS 11 .....

**Comment by mycroes** [comment]
No restrictions that I know of, but please report back if you run into any issues.

**Comment by sebetci** [comment]
Testing was successful on the following product:

| Firm | Product | Operating System |
|:-:|:-:|:-:|
| Yaskawa | [Panel PC](https://www.yaskawa.co.uk/products/hmi/seriesdetail/serie/panel-pc_1260) | Windows 10 IoT Enterprise |
