### ISSUE TITLE
Duplicated code and S7.Net.Core

### ISSUE THREAD

**Issue by mesta1** [killnine/s7netplus#56]
I would like to unify the source files and use `#ifdef NETFX_CORE` to check if use the .Net socket or the custom one.
Also we can use #ifdef to define the correct behaviour for the properties IsAvailable and IsConnected.
Any idea ?

**Comment by killnine** [comment]
Is this related to issue https://github.com/killnine/s7netplus/issues/29?

I'm not entirely sure why we're forced to use a custom implementation in the first place. UWP seems to support TCP sockets, just not between different apps.

**Comment by mesta1** [comment]
Issue #36

**Comment by mesta1** [comment]
@watashimeandeu What problems did you have on using the .Net sockets in .Net Core applications ?

**Comment by watashimeandeu** [comment]
No problem, i think.
SocketClient is using .Net Socket but the idea was change the less code as possible on PLC class by creating the methods send and receive synchronous and returning the bytes transferred.
I use [this](https://msdn.microsoft.com/en-us/library/windows/apps/hh202858(v=vs.105).aspx) as example.

**Comment by mesta1** [comment]
Ok I'll see what I can do with #ifdef.

**Comment by mesta1** [comment]
@watashimeandeu please test .Net Core version.

**Comment by watashimeandeu** [comment]
So far, so good.
