### ISSUE TITLE
Reading Boolean and String

### ISSUE THREAD

**Issue by tanner-wood** [killnine/s7netplus#6]
I have string and bool values inside of a datablock and am unable to read them. The read method accepts an integer byte offset but my string and bool values are decimal based offsets. How do I read these?

![s7netplus strings and bools](https://f.cloud.github.com/assets/2664082/1299505/05648240-3104-11e3-8a53-6a83fc172404.png)

**Comment by oiisamiio** [comment]
Watch out! In some cases i get results without 2 Bytes of length (317PNDP).  So i think there is no secure way to handle this in the libary. Better use Array of chars with Count instead strings.

**Comment by mycroes** [comment]
There's support for reading strings with the header in the `StringEx` class (`StringEx.FromByteArray`). Also, that method correctly handles the header: first byte is `size`, second byte is actual string-`length` (the length of the stored string).
