### ISSUE TITLE
Unit tests fail in x86 on .net 4.5.1 casting failures

### ISSUE THREAD

**Issue by KarlDRose-DWFritz** [killnine/s7netplus#68]
doing baseline testing for Dev studio 2013, using .Net 4.5.1 and X86 and getting several failures on casting results. only passed T00_TestSelectBit and T01_WriteAndReadInt16Variable, all the rest failed.
changed PLC constructor to talk to a real S7-300
 plc = new Plc(CpuType.S7300, "127.0.0.1", 0, 2);  // all tests pass
 //plc = new Plc(CpuType.S7300, "192.168.0.1", 0, 2);  // failures happen

Is there something that I need to configure on the PLC

has this been tested with 4.5.1 on Dev Studio 2013?

**Comment by mesta1** [comment]
Tests need to shutdown a service and to start a socket to simulate a plc. 
Maybe you don't have administrator rights or you have some firewall that is preventing the tests to run correctly ?

**Comment by mesta1** [comment]
Closing. The solution is to give admin rights to unit tests. Tests are executed against a real plc simulator.
