### ISSUE TITLE
Can't get it to work with Logo!

### ISSUE THREAD

**Issue by danielblixt** [killnine/s7netplus#7]
Hello!

Is there anyone out there that has got it to work with Siemens Logo! ?
I've tried different setups but can't get it to work. I would be pleased with help with this!

Best regards
Daniel Blixt
Sweden

**Comment by Joppinator** [comment]
The Logo uses the S7-200 Protocol... maybe this is the solution

**Comment by mycroes** [comment]
Closing, no feedback and possible fix suggested.
