### ISSUE TITLE
Reading Bool variable from DB

### ISSUE THREAD

**Issue by mohamaher** [killnine/s7netplus#71]
Hello,

please I am trying to read a Boolean variable from DB by using ( S7NETPLUS ) as in  below method but I couldn't 
 
> try reading FIRST BIT DB1.DBX4.0 

 var VAR_byt = pl.Read(S7.Net.DataType.DataBlock, 1, 4, S7.Net.VarType.Byte,1);
            byte[] x = VAR_byt as byte[];
            x = new byte[7];
            Console.WriteLine("db1.dbx4.0 = {0}", x[0].ToString());

i am kind of new in c# as well .

Thanks in advance.

Maher

**Comment by watashimeandeu** [comment]
Hi,
didn't test it, but hope this helps.

    var db = 1;
    var offset = 4;
    var result = pl.Read($"DB{db}.DBB{offset}.0") as bool;
    
    if (result == null)
        return false;
    else
        return result;

**Comment by mohamaher** [comment]
thank you
