### ISSUE TITLE
Issues on Read / Write S71200

### ISSUE THREAD

**Issue by danieleperugini** [killnine/s7netplus#72]
Hi, i have a problem.
I have a problem on reading / writing on S71200.
For example Read: on S7300 the method Read("DB5.DBW2") address the communication on datablock 5, db word 2... and it works sugar,

S71200 works differently becouse i have not address but memory names...so i'm not able to find a correct addressing.
Like: i have DB5 with named: int_0, int_1 (integers) ... how to read them with S71200?? i get always WrongVarExecption using Read("DB5.int_0")

**Comment by danieleperugini** [comment]
I just found the problem on slot connections....tnx

**Comment by jkubisiowski** [comment]
Hi @danieleperugini  did you manage to read the symbolic variables from the PLC?
