### ISSUE TITLE
Write to bit should be atomic

### ISSUE THREAD

**Issue by sam0737** [killnine/s7netplus#76]
Currently bit writing like DB100.DBX200.3 is done by reading a byte from DB100.DBD200, modify and write the whole back. This is not atomic and unsafe. Any modification in between by other system or PLC itself could be overwritten.

The protocol supports BIT addressing and writing only one bit. (I am going to create a PR)

**Comment by mesta1** [comment]
Thanks for the PR and I would really love to accept it, but it breaks a lot of code.
I will make a review and if you can adapt it I will push into the codebase.
