### ISSUE TITLE
Continuous monitoring of isAvailable and isConnected

### ISSUE THREAD

**Issue by tanner-wood** [killnine/s7netplus#8]
I am attempting to monitor the isAvailable and isConnected properties of the plc object using a timer running in a windows service.

The default of ping.send is a 1000ms timeout. My timer runs at 100ms to watch the plc connection and available properties. My plc logic runs on a 200ms timer so I want to be able to catch the lost connection between iterations of the plc logic.

I modified the isavailable property to use a shorter ping timeout value and so far testing seems to do okay with this but I am on a very short isolated network for testing. When I get to the warehouse to install this I worry that the distance between my panel and my server will be large enough to add in latency issues that may mess up my logic or create a near-race condition type of issue in the timer logic.

![image](https://f.cloud.github.com/assets/2664082/1449861/3a82743c-4270-11e3-8f68-747008648162.png)

Can you suggest a better method of watching these properties? When you rely upon a plc connection in your own projects how do you handle it not being available? Since I am running a windows service I have no UI to alert my user of the issue. All I can do is log and continue looking or just stop the service.

**Comment by mesta1** [comment]
Updated IsConnected and IsAvailable.
