### ISSUE TITLE
Read Array[0..5] of

### ISSUE THREAD

**Issue by SMOWiwam** [killnine/s7netplus#81]
Hello,

I use the read Class and make my own array's in the constructor. The same size is inside the PLC
But I get an An unhandled exception of type 'System.MissingMethodException' occurred in mscorlib.dll
on Activator.CreateInstance(property.PropertyType);

**Comment by SMOWiwam** [comment]
Visual Studio:
public class PC_Test
    {
        //public bool test { get; set; }
        public double[] testreal { get; set; }
        public PC_Test()
        {
            testreal = new double[6];
        }
    }
TIA Portal:
	testreal	Array[0..5] of Real	0.0			False	True	True	True	False

**Comment by mesta1** [comment]
If it is a fixed array, you can probably declare them as 6 consecutive doubles.
ReadClass can't manage arrays at the moment.

**Comment by mesta1** [comment]
This has been fixed in one of the last commits.
