### ISSUE TITLE
The Ping class causes a bluescreen if you stop debugging while a ping is still in progress

### ISSUE THREAD

**Issue by thomasbargetzkuenz** [killnine/s7netplus#87]
Everytime a connection to the plc  is established with the Plc.Open method, the IsAvailable property is checked. If the plc is not reachable the ping needs some time to recognize this. If you now stop debugging in Visual Studio you will get a bluescreen. You can also reproduce this by writing a small console application which pings an non reachable address (without using the S7 library).

Although this isn't a bug of the S7 library, I'd be if the library avoids using the Ping class. Instead just try to connect to the provided IP and catch the SocketException. To provide something like "Destination IP-Address is not available" you could check for the ErrorCode 10060 (see https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx).

You can find some information about the Ping class bug here:

- https://connect.microsoft.com/VisualStudio/feedback/details/721557/bluescreen-process-has-locked-pages-netframework-ping-send
- https://stackoverflow.com/questions/17756824/blue-screen-when-using-ping

Let me know if you want to get rid of the Ping class, then I will send you the changes as a pull request.

**Comment by mesta1** [comment]
Ok I will get these merged.
