### ISSUE TITLE
Read Class with Word and String

### ISSUE THREAD

**Issue by mikestromi** [killnine/s7netplus#88]
Hello,

I have created a class with some words, real, and dwords and a string.
I try to read a class see picture for definitions
All numeric values are correct but the string remains null on read

Can anybody help?
![s7readstring](https://user-images.githubusercontent.com/31240932/29560606-cab0659a-8732-11e7-9e17-57cc53d7782b.png)

**Comment by mesta1** [comment]
I think you have to read the string as an array of bytes and then convert it. In the last version it's possible to read arrays from ReadClass.
