### ISSUE TITLE
ReadMultipleVars don't works with bit values

### ISSUE THREAD

**Issue by delfuria** [killnine/s7netplus#90]
I find this method very usefull, but reading the "bit" values don't works.
Watching at source i have see a "TODO" for this issue, i think that i have found a solution.
Could i make a PR?
Thanks

**Comment by mesta1** [comment]
Sure, just checkout the last version because we just committed the atomic writing for bits.

**Comment by mesta1** [comment]
https://github.com/killnine/s7netplus/pull/117
