### ISSUE TITLE
V0.1.6 bit write to DB don't  work

### ISSUE THREAD

**Issue by SolarisD** [killnine/s7netplus#91]
This code don't work with version v0.1.6 but v0.1.4 it's ok:
`ErrorCode ec = plc.Open();`
`plc.Write("DB10.DBX658.0", 1);`
`plc.Close();`
acces to memory area with v0.1.6 is work good

**Comment by mesta1** [comment]
Tests didn't caught this. 
Fixed in 0.1.7 and added more tests, to cover this scenario.

**Comment by SolarisD** [comment]
Tested with s7-1200 (1215C) and VS Community 2017

**Comment by SolarisD** [comment]
v0.1.7  bit writing is ok
