### ISSUE TITLE
Parameters of the constructor

### ISSUE THREAD

**Issue by SolarisD** [killnine/s7netplus#92]
/*sorry for my english*/
you create te very good lib, but one thing is not easy - parameters of the constructor,  I don't know it when create the plc class
all parameters are used for connecting, and I think it would be more convenient transfer them in to plc.Open() method.
could you consider this option, thanks.

**Comment by mesta1** [comment]
No we will not do that. 
S7.Net has a function called IsAvailable that uses the IP address even when not configured. 
You can fork the project and move the parameters where you want, or you can wrap S7.net in your own class and create a parameterless ctor and initialize the class in the connect method.
