### ISSUE TITLE
V0.1.7 sbyte write to DB don't work

### ISSUE THREAD

**Issue by SolarisD** [killnine/s7netplus#93]
This code don't work with v0.1.7
sbyte sbMaxHW = 22; (signed 8-bit value - short int for PLC)
plc.Write(DataType.DataBlock, 1, iOffset, sbMaxHW);

but this code is working
byte bMaxHW = 22;
plc.Write(DataType.DataBlock, 1, iOffset, bMaxHW);

**Comment by mesta1** [comment]
Yes this is the 8-bit signed type. 
We still have to add support for that.

**Comment by eltigre4jc** [comment]
Any news about this? I need also to write negative numbers to PLC..
Or is there any workaround possible?

**Comment by SolarisD** [comment]
You shoud convert sByte to Byte and write Byte value to PLC

**Comment by mycroes** [comment]
I guess that @SolarisD  means is cast the `sbyte` to `byte` and write the `byte` value. Would this be good enough for you @eltigre4jc?

**Comment by mycroes** [comment]
Closing due to missing feedback. Feel free to reopen.
