### ISSUE TITLE
Reading UDInt or DWord with uint property doesn't read the correct value

### ISSUE THREAD

**Issue by thomasbargetzkuenz** [killnine/s7netplus#95]
The plc DB looks like this:

![image](https://user-images.githubusercontent.com/30795774/33437981-e0669ac0-d5e9-11e7-89af-befe20a68673.png)

The class to read the DB into looks like this:

```csharp
    public class TestPoco
    {
        public bool BoolValue { get; set; }
        public byte ByteValue { get; set; }
        public short IntValue { get; set; }
        public ushort WordValue { get; set; }
        public int DIntValue { get; set; }
        public uint DWordValue { get; set; }
        public double RealValue { get; set; }
    }
```

Read result:

![image](https://user-images.githubusercontent.com/30795774/33438328-c6f59afe-d5ea-11e7-8a61-104e9f57b57d.png)

As you can see the read DWordValue is not correct. The value on the plc is in hex `AAAAD555` which is `2863322453` in decimal. The read decimal value is `1440066218`.

I think the problem is in `Class.GetPropertyValue(Type, bytes[], ref double)`:

```csharp
                case "Int32":
                    numBytes = Math.Ceiling(numBytes);
                    if ((numBytes / 2 - Math.Floor(numBytes / 2.0)) > 0)
                        numBytes++;
                    // hier auswerten
                    uint sourceUInt = DWord.FromBytes(
                        bytes[(int)numBytes + 3],
                        bytes[(int)numBytes + 2],
                        bytes[(int)numBytes + 1],
                        bytes[(int)numBytes + 0]);
                    value = sourceUInt.ConvertToInt();
                    numBytes += 4;
                    break;
                case "UInt32":
                    numBytes = Math.Ceiling(numBytes);
                    if ((numBytes / 2 - Math.Floor(numBytes / 2.0)) > 0)
                        numBytes++;
                    // hier auswerten
                    value = DWord.FromBytes(
                        bytes[(int)numBytes],
                        bytes[(int)numBytes + 1],
                        bytes[(int)numBytes + 2],
                        bytes[(int)numBytes + 3]);
                    numBytes += 4;
                    break;
```

When reading an Int32 the byte ordering is different than reading an UInt32. But if you check the `DWord.FromByteArray` method it looks like this:

```csharp
        public static UInt32 FromByteArray(byte[] bytes)
        {
            return FromBytes(bytes[3], bytes[2], bytes[1], bytes[0]);
        }
```

As you can see here, the ordering for reading a DWord is from byte[3] to byte[0] and not from byte[0] to byte[3].

When I change the code in the `case UInt32` to read from byte[3] to byte[0] I get the correct DWord value:

![image](https://user-images.githubusercontent.com/30795774/33438619-b02a0be2-d5eb-11e7-88d0-914c31976879.png)

**Comment by mesta1** [comment]
Cool, 
can you make a pull request with the fix ?
